<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Kotc.Czech</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Unity.TextMeshPro"><HintPath>../../../KingOfTheCastle_Data/Managed/Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>../../../KingOfTheCastle_Data/Managed/UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>../../../KingOfTheCastle_Data/Managed/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>../../../KingOfTheCastle_Data/Managed/UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule"><HintPath>../../../KingOfTheCastle_Data/Managed/UnityEngine.TextCoreFontEngineModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>../../../KingOfTheCastle_Data/Managed/Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
