"""Reviewed descriptions and dynamically constructed interface messages."""
import json
from pathlib import Path
mod=Path(__file__).resolve().parents[1]
manual=json.loads((mod/'manual.json').read_text(encoding='utf-8'))
additional=mod/'tools/additional-display.json'
if additional.exists():manual.update({s:v['translation'] for s,v in json.loads(additional.read_text(encoding='utf-8')).items()})
manual.update({
'Sure enough, the Bright Stags\' next play, \'The Barons\' Voyage\', shows a thinly-veiled {K0} discovering a magical island and saving it from a demonic horde.':'Další hra Zářivých jelenů, „Plavba baronů“, skutečně líčí dobrodružství postavy, za kterou lze snadno poznat {K0}: objeví kouzelný ostrov a zachrání ho před hordou démonů.',
"Many even start calling you 'the Stone-Faced', partly in reference to the statue, and partly in reference to your expression when someone cracks a joke about the statue.":'Mnozí vám dokonce začínají říkat „Kamenná tvář“. Narážejí tím jak na sochu, tak na váš výraz, když si z ní někdo utahuje.',
'King of the Castle is a social storytelling game you play with either your <b>Twitch stream</b> or with friends via <b>browsers</b>.':'King of the Castle je společenská příběhová hra, kterou můžete hrát s diváky svého <b>streamu na Twitchi</b> nebo s přáteli přes <b>webové prohlížeče</b>.',
'It may be cowardly, but it <i>works.</i> The Stone Maiden wanders around {K0} aimlessly, finding nothing but barred doors and shuttered windows.':'Možná je to zbabělé, ale <i>funguje to.</i> Kamenná panna se bezcílně potuluje po regionu {K0} a nachází jen zatarasené dveře a zavřené okenice.',
'A dozen other Hounds of the Betrayer run alongside you, howling and yipping enthusiastically.':'Po vašem boku běží tucet dalších Ohařů Zrádce, kteří nadšeně vyjí a štěkají.',
'You order the Hounds of the Betrayer to take off their silly masks and bow down to their {K0}.':'Nařídíte Ohařům Zrádce, aby odložili své směšné masky a vzdali hold vaší koruně: {K0}.',
'Though weaponless, {K0} snatches up the scaug and begins tearing it apart with {K1} bare hands.':'Přestože nemá zbraň, {K0} chytí skauga a začne ho trhat na kusy. Jsou to jen {K1} holé ruce proti bestii.',
"The people are upset, referring to <i>you</i> as 'The Dud', though I'm not familiar with the term.":'Lidé jsou rozladění a říkají <i>vám</i> „Nemehlo“, i když nevím, co to slovo znamená.',
'The money-hungry Guild immediately sends an adventurer from {K0} who calls herself Yanesh the Bold.':'Cech lačnící po penězích okamžitě vyšle dobrodružku z regionu {K0}, která si říká Yanesh Smělá.',
'Make sure you tell all your fellow {K0} that <i>we</i> are your friends, not that tyrannical excuse for a {K1}.':'Vyřiďte všem z regionu {K0}, že vaši přátelé jsme <i>my</i>, ne ta tyranská napodobenina – {K1}.',
"Just came by to let you know your {K0} never returned {K1} copy of 'The Amazing Madeline and Her Educated Ferrets'.":'Jen vám připomínám, že {K0} stále má {K1} výtisk knihy „Úžasná Madeline a její vzdělané fretky“ a dosud ho nevrací.',
'Well, <i>I</i> had fun.':'No, pro <i>mě</i> to byla zábava.',
'Are you so foolish to think <i>we</i> are foolish enough to carry out an exposed conspiracy?':'To si vážně myslíte, že <i>my</i> jsme tak hloupí, abychom uskutečnili už odhalené spiknutí?',
"We've bet our life savings on a boat race around the Coast, and <i>I</i> am sure to win the day!":'Vsadili jsme své životní úspory na závod lodí kolem Pobřeží a <i>já</i> mám vítězství jisté!',
"He wouldn't have invented this snack if <i>I</i> hadn't specifically requested a convenient meal!":'Tuhle svačinu by nevymyslel, nebýt <i>mé</i> žádosti o jídlo, které se dá sníst pohodlně!',
'The High Inquisitor will be furious, but this <i>will</i> help the Church recoup its lost funding.':'Vrchní inkvizitor bude zuřit, ale církvi to <i>pomůže</i> získat zpět ztracené prostředky.',
'<i>SMACK!</i>':'<i>PLESK!</i>',"Well, <i>I</i> don't!":'Ale <i>já</i> ne!',
'<i>Lots</i> of leeches.':'<i>Spousta</i> pijavic.','<i>Most</i> interesting.':'<i>Nanejvýš</i> zajímavé.',
'<i>ahem</i>... surrender.':'<i>ehm</i>… vzdát se.','<i>I</i> committed murder?':'<i>Já</i> že mám na svědomí vraždu?',
'I <i>am</i> pretty amazing.':'Moje schopnosti jsou <i>opravdu</i> úžasné.',
'But <i>I</i> need aid right now!':'Ale <i>já</i> potřebuji pomoc hned teď!',
'Sorry, <i>we</i> committed murder.':'Promiňte, tu vraždu máme na svědomí <i>my</i>.',
'And ensure <i>we</i> get all the credit!':'A zajistěte, aby všechny zásluhy připadly <i>nám</i>!',
"And we'll ensure <i>we</i> get all the credit!":'A postaráme se, aby všechny zásluhy připadly <i>nám</i>!',
"Don't <i>I</i> get to choose who replaces you?":'Nemám snad <i>já</i> rozhodovat o tom, kdo vás nahradí?',
'When did <i>we</i> start caring about equality?':'Odkdy <i>nám</i> záleží na rovnosti?',
"Oh, don't worry, <i>I</i> am a law-abiding citizen.":'Nebojte se, <i>já</i> zákony dodržuji.',
"When it ended, even <i>I</i> wasn't sure who had won.":'Když to skončilo, ani <i>mně</i> nebylo jasné, kdo vyhrál.',
'♫ You have never been / a Queen as <i>I</i> am seen. ♫':'♫ Tobě koruna nesedí / <i>já</i> v ní zářím, lidé vědí. ♫',
'I said <i>de</i>-militarize, not <i>re</i>-militarize!':'Řeč byla o <i>de</i>militarizaci, ne o <i>re</i>militarizaci!',
'<i>I</i> definitely still rule over my estate, not her.':'Nad svým panstvím pořád vládnu <i>já</i>, nikoli ona.',
'Whatever <i>we</i> might think, the {K0} believe in her.':'Ať si <i>my</i> myslíme cokoli, {K0} v ni věří.',
'Encourage the {K0} to pray <i>extra</i> hard from now on.':'Povzbuďte {K0}, aby se od nynějška modlili <i>ještě usilovněji</i>.',
"<i>I</i> can back up the Patricians' accusations, in fact.":'Obvinění patricijů mohu potvrdit i <i>já</i>.',
'<i>I</i> was the one who made those businesses profitable!':'Právě díky <i>mně</i> začaly ty podniky vydělávat!',
'<i>I</i> had a letter from {K0} saying {K1} saw this island first.':'Právě <i>já</i> mám dopis od {K0}, podle kterého tento ostrov jako první spatřil {K1}.',
"Her coins are so convincing even <i>I</i> can't tell the difference.":'Její mince jsou tak věrohodné, že ani <i>já</i> nepoznám rozdíl.',
"But he wasn't expecting to find a <i>troldenfolk</i> in your kitchen!":'Jenže nečekal, že ve vaší kuchyni najde <i>troldenfolka</i>!',
'Obviously <i>I</i> would never partake, but I thought you should know.':'Samozřejmě že pro <i>mě</i> to nepřipadá v úvahu, ale měli byste o tom vědět.',
'I was thinking - what if <i>we</i> did something to make things better?':'Co kdybychom pro zlepšení situace něco udělali <i>my</i>?',
'But you will return, and <i>we</i> will make sure the people know that.':'Vy se ale vrátíte a <i>my</i> se postaráme, aby o tom lidé věděli.',
'We all know <i>I</i> should be on the throne, not this impostor {K0} {K1}.':'Všichni víme, že na trůnu mám sedět <i>já</i>, a ne tahle napodobenina: {K0} {K1}.',
"But why should <i>we</i> have to pay for <i>them?</i> They're <i>{K0}.</i>":'Proč ale máme <i>my</i> platit za <i>ně?</i> Jsou to přece <i>{K0}.</i>',
", well, some of us are contributing a <i>bit</i> more than others, that's all.":', no, někteří z nás přispívají <i>o něco</i> víc než ostatní, to je všechno.',
'The <i>Ulthrandr!</i> Werebeasts who are opposed to the Ninth Church in the North!':'<i>Ulthrandrové!</i> Zvířecí měňavci, kteří se na Severu stavějí proti Deváté církvi!',
"This 'portal' is on my land, so <i>I</i> have the rights to any riches it may contain.":'Ten „portál“ leží na mé půdě, takže na veškeré jeho bohatství mám právo <i>já</i>.',
'We informed the {K0} that <i>we</i> had paid for those weapons they were pointing at us.':'Upozornili jsme {K0}, že zbraně, kterými na nás míří, jsme zaplatili <i>my</i>.',
'After it becomes clear that these laws <i>will</i> be enforced, the peasants get the point.':'Jakmile se ukáže, že se dodržování těchto zákonů <i>bude</i> vymáhat, sedláci pochopí, jak se věci mají.',
'Cultists of the Undivided':'Kultisté Nedělitelného','Disciples of the Tenth':'Učedníci Desátého',
"Barons' Barley of Bliss":'Baronský ječmen blaženosti','Cabbage of Eastern Tranquillity':'Zelí východního klidu',
'the Order of the Wilted Ring':'Řád zvadlého kruhu','the Swords of Emmeline':'Meče Emmeline','the Wings of Chyler':'Křídla Chylera',
'Sisterhood of Steel glide':'oddíl Sesterstva oceli','the Republic of Kirth':'Kirthská republika',
'a Zykerian black pearl':'zykerijská černá perla',"a rare Eastern herb, known as Sashara's Tears":'vzácná východní bylina známá jako Sashariny slzy',
'a small vial of Tajorran frankincense':'malá lahvička tajorranského kadidla','the pickled finger of an ice giant':'naložený prst ledového obra',
'the powdered tusk of a Greater Black Marchboar':'rozemletý kel velkého černého pohraničního kance',
'What. The. Hell?':'Co to má sakra znamenat?',
'A Nice Soak':'Příjemná koupel','A Capital Show':'Velkolepá podívaná',
'A Divisive Crop':'Úroda, která působí rozkol','A Little Mishap':'Drobná nehoda',
'Murder Most Foul':'Ohavná vražda','A Saalish Assassin':'Sálišský vrah',
'STOMP {K0} FLAT!':'ROZDUPAT {K0} NA PADRŤ!',
'Senior Game Scout':'Vedoucí vyhledávání nových her','Game Scout Manager':'Manažer vyhledávání nových her',
'Senior Video Editor':'Seniorní střihač videa','Junior Video Editor':'Juniorní střihač videa',
'Brand Franchise Manager':'Manažer značky a série','Junior User Researchers':'Juniorní výzkumníci uživatelské zkušenosti',
'Senior Compliance Analysts':'Seniorní analytici souladu s předpisy',
'Associate Outsource Producer':'Asistent produkce externích dodavatelů','Associate Development Manager':'Zástupce vedoucího vývoje',
'Senior Influencer Relations Manager':'Vedoucí spolupráce s influencery',
'Ragnarok. (Goal: Raise Own Military)':'Ragnarok. (Cíl: posílit vlastní vojsko)',
'The {K0} <i>will</i> be pleased!':'To {K0} <i>jistě</i> potěší!',
'You <i>will</i> want to hear this.':'Tohle si <i>určitě</i> budete chtít vyslechnout.',
'He will submit or he <i>will</i> be destroyed.':'Buď se podvolí, nebo <i>bude</i> zničen.',
'Actually, I <i>will</i> take some blunderbusses.':'Vlastně si pár trombonů <i>vezmu</i>.',
'<i>I,</i> on the other hand, will <i>never</i> betray the East.':'<i>Já</i> naproti tomu Východ <i>nikdy</i> nezradím.',
'They excel at hit-and-run tactics and leaving traps for the enemy.':'Vynikají v rychlých přepadech s následným ústupem a v kladení pastí na nepřítele.',
'Maybe we <i>will</i> fall in love, once we get to know each other?':'Možná se <i>opravdu</i> zamilujeme, až se lépe poznáme?',
'Grumbling, the {K0} turn their attention to business with the {K1}.':'{K0} s reptáním obrátí pozornost k obchodům s {K1}.',
"It's short for 'May-I-be-smote-by-the-Ninth-if-I-ever-prove-unworthy'.":'Je to zkratka pro „Ať mě Devátý srazí, pokud se kdy ukážu nehodným“.',
'However, your over-the-top reaction has made you even more enemies in {K0}.':'Vaše přehnaná reakce vám však nadělala ještě více nepřátel v regionu {K0}.',
'opens a series of state-of-the-art barracks, cutting the ribbon at each one.':'otevře několik nejmodernějších kasáren a u každých slavnostně přestřihne pásku.',
'Eventually other Nobles <i>will</i> find out, and it will be a scandal - trust me.':'Ostatní šlechtici se to <i>nakonec</i> dozvědí a bude z toho skandál. Věřte mi.',
's':'','es':'',"'s":'', # English verb/possessive suffixes have no Czech equivalent.
'As a result, the Counts double down.':'V důsledku toho hrabata ještě přitvrdí.',
'In the end, the':'Nakonec','The Crawlers Attack':'Útok plazivců','The Siege Grinds On':'Obléhání pokračuje',
'Her name is Yanesh the Bold.':'Jmenuje se Yanesh Smělá.',
"Perhaps I should call myself '{K0} the Bookbinder'.":'Možná by mi slušelo jméno „{K0} Knihař“.',
"The commonfolk start calling you '{K0} the Monstrous'.":'Prostý lid vám začíná říkat „{K0} Obluda“.',
'First is {K0} the Cunning, who won every bout last year!':'První je {K0} Lstivý, který loni vyhrál každý zápas!',
"Rumours say the site is informally called 'The Silver Ours'.":'Podle pověstí místo neoficiálně nazývají „Naše stříbro“.',
"However, some of the {K0} are calling you '{K1} the Miserly'.":'Někteří lidé z regionu {K0} vám však říkají „{K1} Skrblík“.',
'In the end, the {K0} are forced to light a <i>lot</i> of fires.':'Nakonec musejí {K0} zapálit <i>spoustu</i> ohňů.',
'Egad, the {K0} are more important to the Church than <i>us?!</i>':'Pro všechno na světě! {K0} jsou pro církev důležitější než <i>my?!</i>',
'Aye!':'Ano!','Aye.':'Ano.','Aye, aye, keep your hat on.':'Ano, ano, jen klid.',
'Baroness':'Baronka','Barone':'Baron','Countess':'Hraběnka','Conte':'Hrabě','Lord Patrician':'Patricij','Lady Patrician':'Patricijka','Noble Patrician':'Patricij',
'Expedition Soldier':'Voják výpravy','Glorb':'Glorb','Helaena':'Helaena','success':'úspěch','failure':'neúspěch','Success':'Úspěch','Failure':'Neúspěch',
' of ':' – ',' too ':' příliš ',"'s Heir":' – dědic',
'Meat and Two Breads':'Maso a dva krajíce','Footlong':'Třiceticentimetrový sendvič','Footlongs':'Třiceticentimetrové sendviče','Prince':'Princ','Princess':'Princezna',
'Abundant':'Hojnost','Aggrieved':'Uraženost','Agnostic':'Agnosticismus','Aloof':'Odstup','Anarchic':'Anarchie','Barren':'Neúroda','Bountiful':'Bohatá úroda','Capable':'Schopnost','Civil':'Slušnost','Commanding':'Rozhodnost','Cordial':'Srdečnost','Cornucopia':'Roh hojnosti','Credible':'Důvěryhodnost','Desperate':'Zoufalství','Destitute':'Bída','Devout':'Zbožnost','Dominant':'Převaha','Dubious':'Pochybnosti','Dutiful':'Svědomitost','Dynamic':'Rozmach','Enraged':'Rozzuření','Fanatical':'Fanatismus','Feeble':'Chabost','Fertile':'Úrodnost','Fervent':'Vroucnost','Fruitful':'Plodnost','Furious':'Zuřivost','Grumbling':'Reptání','Heathen':'Pohanství','Helpless':'Bezmoc','Imperious':'Panovačnost','Impious':'Bezbožnost','Inadequate':'Nedostatečnost','Ineffective':'Neúčinnost','Insolent':'Drzost','Ironfisted':'Železná pěst','Irreverent':'Neúcta','Lawless':'Bezpráví','Loyal':'Věrnost','Meagre':'Nedostatek','Mediocre':'Průměrnost','Mighty':'Velká síla','Mocked':'Výsměch','Modest':'Skromnost','Monopoly':'Monopol','Mutinous':'Vzpoura','Needful':'Nouze','Oppressive':'Útlak','Opulent':'Hojné bohatství','Pathetic':'Žalostný stav','Peaceful':'Mír','Poor':'Chudoba','Powerful':'Moc','Prosperous':'Prosperita','Rampant':'Bujení','Serene':'Klid','Skeptical':'Skepticismus','Spineless':'Zbabělost','Stable':'Stabilita','Starving':'Hladomor','Steadfast':'Neochvějnost','Steady':'Vyrovnanost','Strong':'Síla','Struggling':'Strádání','Sufficient':'Dostatek','Teetering':'Vratkost','Terrifying':'Hrůza','Treasonous':'Zrada','Turbulent':'Nepokoje','Tyrannical':'Tyranie','Unbeatable':'Neporazitelnost','United':'Jednota','Unstable':'Nestabilita','Vengeful':'Pomstychtivost','Weak':'Slabost','Wealthy':'Bohatství','Zealous':'Horlivost',
'increased':'zvýšení','decreased':'snížení','higher':'výše','lower':'níže',
"{0}'s {1}":'{1} ({0})','{0} has {1}!':'{0}: {1}!','{0} is now {1}!':'{0}: {1}!',"{0} can't go {1}!":'{0} už nemůže jít {1}!',
'Some {0} {1}':'{1} části obyvatel regionu {0}',
'{0} gain {1}!':'{0}: zisk – {1}!','{0} gain a {1}!':'{0}: zisk – {1}!',
'{0} has died.':'{0}: úmrtí.','{0} has been imprisoned.':'{0}: uvěznění.','{0} has joined the Council!':'{0}: vstup do rady!',
'OPEN TO {0} ONLY':'POUZE PRO REGION {0}','+ {0} others':'+ {0} dalších','Noble {0}':'Šlechtic {0}',
'of the {0} DYNASTY':'z DYNASTIE {0}','{0} of the {1} Dynasty':'{0} z dynastie {1}',
'End of Turn':'Konec tahu','End of Year':'Konec roku','End {0}':'Ukončit: {0}','Continue to {0}':'Pokračovat: {0}',
'Treasury too Low!':'V pokladně není dost peněz!','No loyal regions!':'Žádný věrný region!','Confirm Tax':'Potvrdit daň',
'Set Law':'Stanovit zákon','Select Choice':'Vybrat možnost','Setting choice For {0} . . .':'Výběr možnosti pro {0}…',
'Currently Selected':'Právě vybráno','Currently Selected Law':'Aktuálně platný zákon','In rebellion!':'Ve vzpouře!',
'Join the game at www.kotc.app using the room code.':'Připojte se do hry na www.kotc.app pomocí kódu místnosti.',
'Type <u>!join</u> in Twitch chat to join the game as a Noble.':'Napište <u>!join</u> do chatu na Twitchi a připojte se do hry jako šlechtic.',
'New Dynasty - players who own the game can change their Region after joining. This is not available after this screen!':'Nová dynastie: hráči, kteří vlastní hru, mohou po připojení změnit svůj region. Po opuštění této obrazovky už to nebude možné!',
'New Dynasty - players who own the game can type <u>!join (region)</u> in Twitch chat to join a specific Region. For example - <u>!join counts</u>':'Nová dynastie: hráči, kteří vlastní hru, se mohou připojit k určitému regionu příkazem <u>!join (region)</u> v chatu na Twitchi. Například: <u>!join counts</u>',
'Your display is now set to ':'Nové nastavení obrazovky: ',
'If unconfirmed, display will revert to previous settings in {0} seconds.':'Pokud změnu nepotvrdíte, obrazovka se za {0} sekund vrátí k předchozímu nastavení.',
'Full screen':'Celá obrazovka','Windowed':'V okně','Borderless':'Okno bez okrajů',
'Rebels Next Season':'Vzpoura v příštím ročním období','If Defiance is above Authority and stability':'Pokud vzdor převyšuje autoritu i stabilitu',
'Rebellion halted':'Vzpoura zastavena','Defiance is Below Authority or stability':'Vzdor je nižší než autorita nebo stabilita',
'Verge of rebellion':'Na pokraji vzpoury','{0} Needed to start a Rebellion':'K zahájení vzpoury je potřeba {0}',
'Hit the Rebellions tab in your browser to rebel!':'Chcete-li se vzbouřit, otevřete v prohlížeči záložku Rebellions!',
'{0} may vote to rebel by typing <b>!rebel.</b>':'{0} mohou hlasovat pro vzpouru příkazem <b>!rebel.</b>',
'{0} voted to Rebel':'{0} hlasovali pro vzpouru','{0} years, {1} months (Year {2} - {3})':'{0} let, {1} měsíců (rok {2} – {3})',
'Party Game':'Společenská hra','Play on Twitch':'Hrát na Twitchi','The {0} are Victorious!':'{0} zvítězili!','The Monarch is Victorious!':'Panovník zvítězil!',
' Dynasty':' – dynastie','RECONNECT TWITCH IN MAIN\nMENU TO CONTINUE THIS SAVE':'PRO POKRAČOVÁNÍ SE V HLAVNÍ NABÍDCE\nZNOVU PŘIPOJTE K TWITCHI','IMPORTED ':'IMPORTOVÁNO ',
'are sorted into {0} in a game':'jsou ve hře zařazeni do regionu {0}','run a game as the reigning Monarch':'vedou hru jako vládnoucí panovník',
'The Loyalists are winning the Rebellion. The Rebels are crumbling…':'Věrní mají ve vzpouře navrch. Povstalci se hroutí…',
'The Kingdom is in Rebellion! The first side to earn <color=#B9172F>5 Victory Points will win. </color>Victory Points are earned through Events. If the Rebels are victorious, the Monarch is overthrown.':'Království zachvátila vzpoura! Zvítězí strana, která jako první získá <color=#B9172F>5 vítězných bodů. </color>Body se získávají při událostech. Pokud zvítězí povstalci, panovník bude svržen.',
'On the verge of Rebellion!':'Na pokraji vzpoury!','Currently Rebelling!':'Právě se bouří!','Cannot start a Rebellion.':'Vzpouru nelze zahájit.',
'Defiance is too low ({0}). Needs to be <b>{1}</b> or higher.':'Vzdor je příliš nízký ({0}). Musí dosáhnout alespoň <b>{1}</b>.',
'Save Exported!':'Uložená hra byla exportována!','Exporting Save...':'Exportování uložené hry…','SHOW CODE':'ZOBRAZIT KÓD',
'An unexpected error has occured.\nPlease restart the game and try again.':'Došlo k neočekávané chybě.\nRestartujte hru a zkuste to znovu.',
"Could not find the save with filename '{0}'.\nPlease ensure you haven't renamed any save files and try again.":"Uložený soubor '{0}' nebyl nalezen.\nOvěřte, zda jste soubory nepřejmenovali, a zkuste to znovu.",
"Could not find a save with code '{0}'.<br>Check the code entered and note that we delete saves after 14 days.":"Uložená hra s kódem '{0}' nebyla nalezena.<br>Zkontrolujte zadaný kód. Uložené hry se po 14 dnech mažou.",
"An unexpected error occurred while retrieving save '{0}'.<br>Check the code entered and note that we delete saves after 14 days.":"Při načítání uložené hry '{0}' došlo k neočekávané chybě.<br>Zkontrolujte zadaný kód. Uložené hry se po 14 dnech mažou.",
'Import saves by entering a code below.<br>We store saves for 14 days before deleting.<br>Note - Twitch Mode saves cannot be played in Party Games and vice versa.':'Pro import uložené hry zadejte níže její kód.<br>Uložené hry se uchovávají 14 dní a potom se mažou.<br>Pozor: uložené hry z režimu Twitch nelze hrát ve společenském režimu a naopak.',
"Importing this save file will overwrite the existing save file for the '{0}' dynasty. Are you sure you want to do this?":"Import přepíše dosavadní uloženou hru dynastie '{0}'. Chcete pokračovat?",
"Save '{0}' imported successfully.":"Uložená hra '{0}' byla úspěšně importována.",
'Import save':'Importovat uloženou hru','Import successful':'Import byl úspěšný','Account link':'Propojení účtu',
'Logging in...':'Přihlašování…','Connecting to game server...':'Připojování k hernímu serveru…','Reconnecting to Twitch...':'Opětovné připojování k Twitchi…',
'<color="red">Could not Login.</color>\nCheck internet connection and retry.':'<color="red">Přihlášení se nezdařilo.</color>\nZkontrolujte připojení k internetu a zkuste to znovu.',
'<color="red">Error connecting to game server.</color>\nPlease try later.':'<color="red">Chyba připojení k hernímu serveru.</color>\nZkuste to později.',
'<color="red">Connection error.</color>\nReconnecting ({0}/{1})...':'<color="red">Chyba připojení.</color>\nOpětovné připojování ({0}/{1})…',
'<color="red">Could not reconnect.</color>\nCheck internet connection and restart.':'<color="red">Připojení se nepodařilo obnovit.</color>\nZkontrolujte připojení k internetu a restartujte hru.',
'Distant Cousin':'Vzdálený příbuzný','False Pretender':'Falešný uchazeč o trůn','Embittered Step-Uncle':'Zahořklý nevlastní strýc','Embittered Step-Aunt':'Zahořklá nevlastní teta','Embittered Step-Sibling':'Zahořklý nevlastní sourozenec','Bastard Offshoot':'Levoboček','Ambitious Vassal':'Ctižádostivý vazal','Questionable Claimant':'Pochybný uchazeč o trůn','Long-Lost Nephew':'Dávno ztracený synovec','Long-Lost Niece':'Dávno ztracená neteř','Long-Lost Nibling':'Dávno ztracený příbuzný','Treacherous Half-Brother':'Zrádný nevlastní bratr','Treacherous Half-Sister':'Zrádná nevlastní sestra','Treacherous Half-Sibling':'Zrádný nevlastní sourozenec',
'Raise':'Zvýšit','Lower':'Snížit',"all regions' total":'součet všech regionů',"other regions' total":'součet ostatních regionů','your own':'vlastní hodnotu',"the Kingdom's":'hodnotu království','Have the Lowest':'Mít ze všech regionů nejnižší','Have the Highest':'Mít ze všech regionů nejvyšší','to at least {0}':'alespoň na {0}','to {0} or less':'na {0} nebo méně','by next season':'do příštího ročního období','in {0} seasons':'do {0} ročních období',
'Ensure the ':'Podpořte panovníka ',"'s Ambition succeeds while thwarting the other regions' Schemes":': splňte jeho cíl vlády a zmařte intriky ostatních regionů',
'Adventurer':'Dobrodruh','Archduke Shomo':'Arcivévoda Shomo','Ashmedean Ambassador':'Ashmedejský vyslanec','Assassin':'Nájemný vrah','Athmorel':'Athmorel','Bard':'Bard','Baron':'Baron','Battle-Nun':'Bojovná jeptiška','Bounty Hunter':'Lovec odměn','Brzzkt':'Brzzkt','Chief':'Náčelník','Chief Architect':'Hlavní architekt','Count':'Hrabě','Crawler Queen':'Královna plazivců','Eastern Knight':'Rytíř z Východu','Etraveon':'Etraveon','Farmer':'Rolník','Finfolk':'Mořský lid','Fire Spirit':'Ohnivý duch','Foreign Mercenary':'Cizí žoldnéř','Gladiator':'Gladiátor','Gordias':'Gordias','Grandee':'Velmož','Guard':'Strážný','High Inquisitor':'Velký inkvizitor','Jester':'Šašek','Kirth Diplomat':'Kirthský diplomat','Knight':'Rytíř','Marcher Soldier':'Voják z Pomezí','Merchant':'Kupec','Northern Warrior':'Válečník ze Severu','Oreid':'Oreid','Ortega':'Ortega','Patrician':'Patricij','Peasant':'Sedlák','Pestia':'Pestia','Pirate Queen':'Pirátská královna','Playwright':'Dramatik','Queen Mother':'Královna matka','Sailor':'Námořník','Scholar':'Učenec','Scrampton':'Scrampton','Servant':'Sluha','Skeleton':'Kostlivec','Soldier':'Voják','Spy':'Špeh','Troll':'Troll','Watch Captain':'Kapitán stráže','Werebeast':'Vlkodlak','Witch':'Čarodějnice','them':'je','it':'to','its':'jeho',
})
for source,target in list(manual.items()):
    if source!=source.strip():manual.setdefault(source.strip(),target.strip())
(mod/'manual.json').write_text(json.dumps(manual,ensure_ascii=False,indent=2),encoding='utf-8')
print('Reviewed manual entries',len(manual))
