import json,re,collections
from pathlib import Path
mod=Path(__file__).resolve().parent.parent
fields=json.loads((mod/'tools/field_inventory.json').read_text(encoding='utf-8'))
manual=json.loads((mod/'manual.json').read_text(encoding='utf-8'))
tutorial=[
'Získejte <b>dědice</b> a potom splňte svůj <b>cíl vlády</b>, abyste zvítězili. Vaše první vláda nejspíš skončí katastrofou. Koruna je těžké břemeno!',
'Všichni šlechtici zde získají bohatství, ale jeden region dostane navíc obchodní bonus. Vyšší hodnota obchodu zvyšuje šanci regionu na tento bonus.',
'Alespoň jeden region postoupil do poslední fáze své intriky. Pokud ji dokončí, vyhraje hru. Existuje však několik výjimek…',
'Vyvažujte potřeby pokladny se změnami vzdoru. Pamatujte, že region se může vzbouřit, pokud jeho vzdor převyšuje autoritu i stabilitu.',
'Dávejte pozor na <b>vzdor regionů</b>! Pokud příliš vzroste, regiony se proti vám mohou <b>vzbouřit</b>.',
'Některá rozhodnutí mění herní hodnoty. U části těchto možností se zde zobrazí značka upozorňující na změnu.',
'Kliknutím na prapory pod „Nastavením regionů“ upravíte vzhled svých šlechticů. Tyto postavy vás budou zastupovat ve hrách ostatních hráčů.',
'Splňte svůj cíl vlády dříve, než vás svrhne intrika nebo vzpoura, případně než přijdete o všechnu autoritu, peníze v pokladně nebo stabilitu.',
'Upravte vzhled svého <b>panovníka</b>, ať má vaše vláda osobitý styl, a poté založte <b>novou dynastii</b>.',
'Upravte vzhled svého <b>šlechtice</b> a <b>propojte účet na Twitchi</b>. Vaše vlastní postava se pak objeví ve společenských hrách i hrách přes Twitch.',
'Každý region nyní hlasováním vybere jednu ze tří náhodně nabídnutých intrik.',
'V každém ročním období dostanete tři události. Začněte kliknutím na jednu z nich.',
'Zde můžete přijmout nový zákon, který mění pravidla hlasování. Další zákon budete moci přijmout jednou za rok, na konci zimy.',
'Zde si můžete prohlédnout intriky jednotlivých regionů a jejich uchazeče o trůn.',
'Zde můžete každému regionu v království stanovit jinou daň nebo úplatek. Některé tak můžete potrestat a jiné odměnit.',
'Zde můžete upravit vzhled panovníka i šlechticů. Některé úpravy jsou dostupné pouze hráčům, kteří si hru koupili.',
'Je na vás, jak budete hlasovat: můžete podporovat intriku svého regionu, mařit intriky ostatních nebo jednat ve prospěch království.',
'Pokud vzdor převyšuje autoritu i stabilitu, region může vyvolat vzpouru. Tím se pozastaví jeho intrika. S nízkou hodnotou vojska je vzpoura riskantní.',
'Pokud stabilita, autorita nebo pokladna klesne na 0 ve stejnou chvíli, kdy je dokončena poslední fáze intriky, má vítězství intrikou přednost.',
'Pokud stabilita, autorita nebo pokladna klesne na 0, občanskou válku vyhrají povstalci.',
'Pokud vzpoura skončí vítězstvím povstalců ve stejnou chvíli, kdy je dokončena poslední fáze intriky, má vítězství intrikou přednost.',
'Pokud se vzbouří a zvítězí více regionů, o nástupci rozhodne hlasování mezi dvěma vítěznými regiony s nejvyššími herními hodnotami.',
'Pokud věrní získají více vítězných bodů než povstalci, potlačí vzpouru a hra bude pokračovat.',
'Pokud povstalci získají více vítězných bodů než věrní, vyhrají hru.',
'Pokud poslední fázi intriky dokončí dva či více regionů současně, vítěz bude vybrán náhodně.',
'Pokud máte dostatečně vysoký <b>vzdor</b>, můžete se <b>vzbouřit</b>. Tím pozastavíte svou <b>intriku</b>. Vzpoura je riskantní, zvlášť pokud máte slabé <b>vojsko</b>.',
'Pokud vaše vláda náhle skončí, šlechtici hlasováním zvolí dalšího panovníka.',
'Pozor! Intriky vzbouřených regionů se pozastaví.',
'Chcete-li pořádat hry přes Twitch a používat v nich vlastního šlechtice, propojte svůj účet na Twitchi.',
'Sledujte <b>intriky</b> regionů. Pokud dokončí všechny jejich <b>fáze</b>, vyhrají hru.',
'King of the Castle je společenská příběhová hra, kterou můžete hrát s přáteli jako <b>společenskou hru</b> přes prohlížeče nebo se svým <b>chatem na Twitchi</b>.',
'Šlechtici mohou <b>hlasovat</b> o některých rozhodnutích a pomocí <b>intrik</b> vás připravit o trůn. Musíte přežít a zajistit, aby po vás na trůn usedl váš <b>dědic</b>.',
'Šlechtici mohou za své bohatství přihazovat na libovolnou stavbu v kterémkoli regionu. Každá stavba ovlivňuje jednu herní hodnotu.',
'Tyto značky se nezobrazují u všech možností, které mění herní hodnoty. Navíc neukazují, kterého regionu se změna týká!',
'Teď jste odehráli všechny události. Pokračujte kliknutím na „Ukončit roční období“.',
'Jeden nebo více regionů se může vzbouřit, protože jejich vzdor převyšuje autoritu i stabilitu.',
'Naše rozšíření pro Twitch hráčům ukazuje jejich region, bohatství, intriku a další informace. Nainstalujete ho na <u><color=#0000EE><link="https://kotc.app/twitch-extension">kotc.app/twitch-extension</link></color></u>',
'Dokončením všech tří fází intriky region dosadí svého uchazeče na trůn a vyhraje hru.',
'Hráči se mohou <b>připojit</b> do vaší hry jako <b>šlechtici</b> v radě. Pocházejí z jednoho ze tří <b>regionů</b>.',
'Regiony se silnějším vojskem mají větší šanci svrhnout panovníka vzpourou.',
'Intriky se skládají ze tří fází. Každá fáze vyžaduje určité herní hodnoty.',
'Některá rozhodnutí mají nejistý výsledek. Říká se jim zkoušky.',
'Panovník může zákonem změnit pravidla hlasování.',
'Panovník může zvítězit pouze v událostech spojených s cílem vlády. Ty se začnou objevovat po získání dědice.',
'Panovník může hlasování ukončit, jakmile hlasovali všichni šlechtici nebo vypršel časový limit.',
'Panovník musí získat dědice a splnit svůj cíl vlády, aby vyhrál hru. Manžel či manželka vám mohou pomoci, ale nejsou podmínkou vítězství.',
'Toto jsou herní hodnoty království. Pokud je na začátku ročního období kterákoli z nich na 0, hra skončí.',
'Toto jsou herní hodnoty regionu. Určují, které události se budou objevovat.',
'O těchto možnostech budou šlechtici hlasovat. Každá z nich může nějakým způsobem změnit herní hodnoty.',
'Výsledek může být náhodný nebo záviset na některé herní hodnotě. Procento udává šanci na úspěch.',
'Tento hráč si koupil King of the Castle. Může upravovat vzhled své postavy, získat zvláštní oblečení a častěji se objevovat v příbězích.',
'Stavby se vybírají v dražbě. Postaví se pouze dvě, na které se vybralo nejvíce peněz.',
'Toto je váš panovník, tedy postava streamera. Objeví se ve většině příběhů, ale ne ve všech.',
'Na této obrazovce vidíte svou upravenou postavu panovníka. Bude vás jako hlavního hráče nebo streamera zastupovat ve hrách, které pořádáte.',
'Tady vidíte, která herní hodnota se změnila a o kolik.',
'V tomto hlasování se vybírá mezi dvěma regiony s nejvyšším součtem herních hodnot a vaším dědicem, pokud nějakého máte.',
'Abyste zvítězili, dokončete všechny tři fáze své <b>intriky</b>. V každé fázi musíte dostat určité herní hodnoty na požadovanou úroveň. Jejich výši ovlivňují rozhodnutí při hlasování.',
'Během dražby mohou šlechtici přispívat příkazem „!fund a x“, kde x je částka z jejich osobního bohatství.',
'Po zahájení hlasování šlechtici hlasují příkazem „!vote“ a písmenem vybrané možnosti, například „!vote a“.',
'Jakmile získáte dědice, objeví se vpravo na této stránce.',
'Až budete připraveni, kliknutím na „Zahájit dražbu“ spustíte dražbu.',
'Uložené hry můžete také exportovat. Ostatní hráči je pak mohou importovat a hrát na obrazovce „Pokračovat v dynastii“. Ukládáme je na svých serverech, takže není potřeba nic kopírovat a vkládat!',
'Najednou můžete přijmout pouze jeden nový zákon. Současně můžete mít k dispozici nejvýše tři zákony.',
'Zde můžete procházet úplný seznam šlechticů a jejich bohatství.',
'Nyní můžete pokračovat ve hře. Po dokončení hry vznikne nová uložená pozice, ze které můžete navázat na příběh své dynastie.',
'Při každém hlasování můžete použít jeden zákon. Zkuste vetovat možnost, která se vám nelíbí.',
'Hrajete za <b>panovníka</b> fantasy království, procházíte <b>událostmi</b> a činíte rozhodnutí.',
'Svému šlechtici můžete nastavit vlastní erb. Ve větších hrách pak snáze poznáte jeho hlas.',
'Vaši šlechtici se nyní mohou připojit přes chat na Twitchi příkazem „!join“ následovaným zájmenem, například „!join she“ pro ženský rod. Hráči se mohou připojit i během hry. Jejich bohatství a region se zachovají při pokračování z uložené pozice.',
'Vaši šlechtici se vrátí do svých původních regionů a zachovají si bohatství.',
'Ve druhé hře se objeví dynastické události, které navazují na dřívější příběhy.'
]
titles=['Konec při hodnotě 0','Přijmout zákon','Stavby','Zkoušky','Rozhodnutí a herní hodnoty','Uchazeči o trůn','Pokračujte ve své dynastii','Úprava vzhledu','Vzdor','Dynastické události','Ukončit roční období','Události','Hodně štěstí','Dědic a cíl vlády','Jak hrát','Připojte se ke hře!','Hodnoty království','Zákony království','Omezení zákonů','Propojte účet na Twitchi','Vojsko','Panovník','Panovník – vzdor','Panovník – intriky','Panovník – vítězství','Více vzbouřených regionů','Více intrik','Seznam šlechticů','Erby šlechticů','Šlechtici','Šlechtici – vzpoury','Šlechtici – hlasování','Šlechtici – vítězství','Jeden zákon','Hra za panovníka','Hra za šlechtice','Prémioví šlechtici','Vzpoura','Vzpoury','Hodnoty regionu','Daně regionů','Návrat šlechticů','Import a export uložených her','Fáze intriky','Intriky','Pozastavené intriky','Změny herních hodnot','Hlasování o nástupci','Daně','Závěr hry','Panovník','Šlechtici','Časový limit','Obchodní bonus','Rozšíření pro Twitch','Vítězné body','Hlasování','Co je King of the Castle?','Jak vyhrát hru','Váš dědic']
wealth=[
'Nová móda plášťů vynesla hrabatům BigChange bohatství.',
'Po potyčce s ledovými obry získali náčelníci kořist v hodnotě BigChange bohatství.',
'Baroni se spojili s místním žoldnéřským cechem a vydělali BigChange bohatství.',
'Baroni rozumně investovali do obchodu s kožešinami a vydělali BigChange bohatství.',
'Baroni vydělali BigChange bohatství prodejem kůží zvířat, která svou činností přivedli na pokraj vyhynutí.',
'Baroni prodali zásobu zbraní do Tatterlands a pořádně na tom vydělali: BigChange bohatství!',
'Baroni neochvějně popírají, že Ashmede prodali zbraně za BigChange bohatství.',
'Baroni v kopcích narazili na bohatou žílu železné rudy a získali BigChange bohatství.',
'Nové „horké koláče“ baronů jdou na dračku a vynesly BigChange bohatství!',
'Náčelníci objevili prastarý poklad zamrzlý v ledu, v hodnotě BigChange bohatství.',
'Náčelníci vynalezli nový druh mimořádně silné medoviny a vydělali BigChange bohatství.',
'Náčelníci rozumně investovali do místních pivovarů a vydělali BigChange bohatství.',
'Náčelníci vydělali BigChange bohatství sběrem vzácných hub.',
'Náčelníci uzavřeli dohodu se sítí pil a vydělali BigChange bohatství.',
'Náčelníci v horách narazili na bohatou žílu železa a získali BigChange bohatství.',
'Hrabata vykácela část lesa, aby postavila nové mlýny, a vydělala BigChange bohatství.',
'Hrabata objevila novou bohatou žílu měděné rudy a získala BigChange bohatství.',
'Hrabata v dávno opuštěné kryptě objevila poklad v hodnotě BigChange bohatství.',
'Hrabata uvalila na své nevolníky kruté daně a získala BigChange bohatství.',
'Hrabata prodala prokletou modlu důvěřivým daneanským kupcům za BigChange bohatství.',
'Hrabata prodala nevyužívané pozemky cechu dobrodruhů za BigChange bohatství.',
'Velmoži v poušti vykopali zakopaný poklad v hodnotě BigChange bohatství.',
'Velmoži objevili levnou metodu výroby barviv a ušetřili BigChange bohatství.',
'Velmoži rozumně investovali do vývozu parfémů a vydělali BigChange bohatství.',
'Velmoži získali BigChange bohatství díky několika chytrým investicím.',
'Velmoži obdrželi BigChange bohatství „od Devátého boha“. Máte podezření na daňový podvod.',
'Velmoži uzavřeli výnosnou obchodní dohodu s Kirth v hodnotě BigChange bohatství.',
'Vinice velmožů daly bohatou úrodu a vynesly BigChange bohatství.',
'Patricijové našli útes plný perlorodek a vydělali BigChange bohatství.',
'Patricijové vynalezli „pojištění“ a vydělali BigChange bohatství, zatímco pobřeží sužují požáry.',
'Patricijové rozumně investovali do vývozu vína a vydělali BigChange bohatství.',
'Patricijové vydělali BigChange bohatství prodejem bezcenných akcií důvěřivým sedlákům.',
'Patricijové vydělali BigChange bohatství prodejem zázračného mastičkářského léku, který údajně léčí krtici.',
'Patricijové uzavřeli výnosnou obchodní dohodu se Saal v hodnotě BigChange bohatství.',
'Rybolov patricijům v tomto čtvrtletí vynesl BigChange bohatství.'
]
for field,targets in [('sections.[].text',tutorial),('sections.[].title',titles),('wealthBumpReasons.[]',wealth)]:
    assert len(fields[field])==len(targets),(field,len(fields[field]),len(targets))
    for source,target in zip(fields[field],targets):
        assert collections.Counter(re.findall(r'<[^>]+>',source))==collections.Counter(re.findall(r'<[^>]+>',target)),source
        if 'BigChange' in source:assert 'BigChange' in target
        manual[source.strip()]=target
manual.update({'Your Nobles may now join the game at <b>www.kotc.app</b> using the room code above.':'Vaši šlechtici se nyní mohou připojit do hry na <b>www.kotc.app</b> pomocí kódu místnosti zobrazeného výše.',
"When the Auction is open, Nobles can fund through the browser in increments of 100.":'Během dražby mohou šlechtici přispívat přes prohlížeč v násobcích 100.',
"When the vote opens, Nobles vote on which choice they want in the browser.":'Po zahájení hlasování šlechtici vyberou v prohlížeči možnost, pro kterou chtějí hlasovat.'})
(mod/'manual.json').write_text(json.dumps(manual,ensure_ascii=False,indent=2),encoding='utf-8')
print('Manual total',len(manual))
